### PR TITLE
Feature/recipe class

### PR DESCRIPTION
**Pull request by elizhahn**
## Is this a fix or a feature?
- feature

## What is the change?
- a Recipe class was added and testing suite
## What does it fix?
- N/A
## Where should the reviewer start?
- recipe.js
- recipe-test.js
## How should this be tested?
- run npm test from root directory, all tests should be passing

### CODE REVIEW

**Comment by alexthompson207** [comment]
Looks good, I would change all the `"` to `'` double to single quotes to match the linter.

**Comment by elizhahn** [comment]
I made that change, and deleted a comment that was still in there as well.

**Comment by elizhahn** [comment]
My prettier package changed the quotes all back to double, I had to recommit those changes, it should be good now!

**Review by alexthompson207 — COMMENTED** [review]
Looks good!

**Pull request merged**
